[book]
authors = ["Julia Benisty", "Clement Delafargue", "Geoffroy Couprie"]
language = "en"
multilingual = false
src = "src"
title = "Biscuit"

[output.html.playground]
runnable = false
git-repository-url = "https://github.com/biscuit-auth/biscuit"
git-repository-icon = "fa-github"
