on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies and build web components
        run: |
          cd wc/
          npm install
          npm run build
          ls ../static
          ls ../static/assets
          cd ..
      - name: Install Zola
        run: |
          sudo snap install --edge zola
      - name: Build
        run: |
          zola build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.CELLAR_BUCKET }}
          AWS_S3_ENDPOINT: https://cellar-c2.services.clever-cloud.com/
          AWS_ACCESS_KEY_ID: ${{ secrets.CELLAR_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CELLAR_KEY_SECRET }}
          SOURCE_DIR: 'public'

