on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies and build web components
        run: |
          cd wc/
          npm clean-install
          npm run build
          ls ../static
          ls ../static/assets
          cd ..
      - name: Install MermaidJS CLI
        run: |
          npm install @mermaid-js/mermaid-cli
          ./mmd.sh
      - name: Install Zola
        run: |
          #sudo snap install --edge zola
          curl -L https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz -o zola.tar.gz
          tar xvf zola.tar.gz
      - name: Build website
        run: |
          ./zola build
      - name: Install mdbook
        run: |
          curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.28/mdbook-v0.4.28-x86_64-unknown-linux-gnu.tar.gz -o mdbook.tar.gz
          tar xvf mdbook.tar.gz
      - name: Build docs
        run: |
          ./mdbook build docs
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.CELLAR_BUCKET }}
          AWS_S3_ENDPOINT: https://cellar-c2.services.clever-cloud.com/
          AWS_ACCESS_KEY_ID: ${{ secrets.CELLAR_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CELLAR_KEY_SECRET }}
          SOURCE_DIR: 'public'
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.CELLAR_DOCS_BUCKET }}
          AWS_S3_ENDPOINT: https://cellar-c2.services.clever-cloud.com/
          AWS_ACCESS_KEY_ID: ${{ secrets.CELLAR_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CELLAR_KEY_SECRET }}
          SOURCE_DIR: 'docs/book'

